server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-IDENTITY-SERVICE
          url: lb://USER-IDENTITY-SERVICE
          predicates:
            - Path=/api/**
#        - id: DEPARTMENT-SERVICE
#          url: lb://DEPARTMENT-SERVICE
#          predicates:
#            - Path=/departments/**


  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost